# ====================================
# Hyperledger Fabric Configuration
# ====================================

FABRIC_VERSION="3.1.1"

FABRIC_CA_VERSION="1.5.15"

FABRIC_SAMPLES_DIR="$HOME/hyperledger/fabric-samples"

CHANNEL_NAME="mychannel"

CHAINCODE_NAME="basic"

CHAINCODE_LANGUAGE="go"