# ====================================
# Paths
# ====================================

FABRIC_HOME="$HOME/hyperledger"

GENERATED_NETWORKS="$FABRIC_HOME/generated/networks"

GENERATED_CHAINCODES="$FABRIC_HOME/generated/chaincodes"

GENERATED_REPORTS="$FABRIC_HOME/generated/reports"